/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import dataTools.DataReader;
import dataTools.DataWriter;
import java.util.ArrayList;
import ffrag.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 21611924
 */
public class Organisateur_InscriptionValide extends javax.swing.JFrame {

    /**
     * Creates new form InscriptionValide
     */
    public Organisateur_InscriptionValide(String nomR,String lieu,String edition, String datedeb, String dateFin, 
            String nomC, String prenomC, String dateN, String GroupeS, String Rh,String nomV,String idV, boolean voiture, String puissance, String poids) {
        
        initComponents();
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        this.jLabelSysdate.setText(df.format(d));
        this.NomRallye.setText(nomR);
        this.lieu.setText(lieu);
        this.Edition.setText(edition);
        this.dateDebut.setText(datedeb);
        this.dateFin.setText(dateFin);
        this.nomCoureur.setText(nomC);
        this.prenomCoureur.setText(prenomC);
        this.dateN.setText(dateN);
        this.jLabelGroupeSanguin.setText(GroupeS);
        this.labelBooleanRh.setText(Rh);
        this.idVehicule.setText(idV);
        this.jLabelNomVehicule.setText(nomV);
        if(voiture == true){
            this.vehicule.setText("voiture");
            this.vehiculeP.setText("puissance");
            this.vehiculeA.setText(puissance);
        }else{
            this.vehicule.setText("camion");
            this.vehiculeP.setText("poids");
            this.vehiculeA.setText(poids);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelSysdate = new javax.swing.JLabel();
        dateDebut = new javax.swing.JLabel();
        dateFin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NomRallye = new javax.swing.JLabel();
        Edition = new javax.swing.JLabel();
        lieu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        prenomCoureur = new javax.swing.JLabel();
        nomCoureur = new javax.swing.JLabel();
        dateN = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idVehicule = new javax.swing.JLabel();
        vehicule = new javax.swing.JLabel();
        vehiculeA = new javax.swing.JLabel();
        jButtonValiderIns = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        vehiculeP = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelGroupeSanguin = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelNomVehicule = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelBooleanRh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Validation Inscription");

        jLabelSysdate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelSysdate.setText("Sysdate");

        dateDebut.setText("dateDebutAfficher");

        dateFin.setText("dateFinAfficher");

        jLabel2.setText("Nom du Rallye");

        jLabel3.setText("Lieu");

        jLabel4.setText("No.Edition");

        jLabel5.setText("dateDebut");

        jLabel6.setText("dateFin");

        NomRallye.setText("Rallye");

        Edition.setText("Edition");

        lieu.setText("lieu");

        jLabel8.setText("Nom");

        jLabel9.setText("Prenom");

        jLabel10.setText("dateNaissance");

        prenomCoureur.setText("prenom");

        nomCoureur.setText("nom");

        dateN.setText("DateN");

        jLabel12.setText("Numéro Immatriculation");

        idVehicule.setText("numero");

        vehicule.setText("vehicule");

        vehiculeA.setText("puissance/poid");

        jButtonValiderIns.setText("Valider");
        jButtonValiderIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValiderInsMouseClicked(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRetourMouseClicked(evt);
            }
        });

        vehiculeP.setText("vehicule");

        jLabel11.setText("GroupeSanguin");

        jLabelGroupeSanguin.setText("GroupeSanguin");

        jLabel13.setText("Nom Vehicule");

        jLabelNomVehicule.setText("Nom Vehicule");

        jLabel14.setText("Type Vehicule");

        jLabel15.setText("Rhesus");

        labelBooleanRh.setText("BooleanRh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(11, 11, 11)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomCoureur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prenomCoureur, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(dateN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelGroupeSanguin)
                            .addComponent(labelBooleanRh)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButtonRetour)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonValiderIns)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(vehiculeP)
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addGap(53, 53, 53)))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicule)
                                    .addComponent(vehiculeA)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12))
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNomVehicule)
                                        .addComponent(idVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(50, 50, 50)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                    .addGap(50, 50, 50)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(NomRallye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Edition, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(15, 15, 15)))
                                    .addGap(6, 6, 6))))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelSysdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSysdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NomRallye))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lieu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Edition))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateDebut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(prenomCoureur)
                        .addGap(18, 18, 18)
                        .addComponent(dateN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomCoureur)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelGroupeSanguin))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelBooleanRh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(idVehicule))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelNomVehicule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicule)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiculeP)
                    .addComponent(vehiculeA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValiderIns)
                    .addComponent(jButtonRetour))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderInsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        /*
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date di = new Date();
        Date dn = new Date();
        try {
            di = df.parse(this.jLabelSysdate.getText());
            dn = df.parse(this.dateN.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Organisateur_InscriptionValide.class.getName()).log(Level.SEVERE, null, ex);
        }
        Coureur c = new Coureur(this.nomCoureur.getText(),this.prenomCoureur.getText(),dn);
        Vehicule v;
        if(this.vehicule.getText().equals("voiture")){
            v = new Voiture(this.idVehicule.getText(),Integer.parseInt(this.vehiculeA.getText()));
        }else{
            v = new Camion(this.idVehicule.getText(),Integer.parseInt(this.vehiculeA.getText()));
        }
        
        Participant p = new Participant(di,v,c);
        System.out.print(p.toString());
        */
        File fileParticipant  = new File("src/csv/Participant.csv");
        DataWriter dw = new DataWriter();
        ArrayList<String> listInfoP = new ArrayList<String>();
        System.out.print(this.NomRallye.getText());
        listInfoP.add(this.NomRallye.getText());
        listInfoP.add(this.Edition.getText());
        listInfoP.add(this.jLabelSysdate.getText());
        listInfoP.add(this.nomCoureur.getText());
        listInfoP.add(this.prenomCoureur.getText());
        listInfoP.add(this.dateN.getText());
        listInfoP.add(this.jLabelGroupeSanguin.getText());
        if(this.labelBooleanRh.getText()=="oui"){
            listInfoP.add("+");
        }
        else{
            listInfoP.add("-");
        }
        listInfoP.add(this.jLabelNomVehicule.getText());
        listInfoP.add(this.idVehicule.getText());
        listInfoP.add(this.vehicule.getText());
        listInfoP.add(this.vehiculeA.getText());
        listInfoP.add("10");
        
        //fileParticipant.setWritable(true);
        dw.writeCsv(fileParticipant, listInfoP);
        
    }//GEN-LAST:event_jButtonValiderInsMouseClicked

    private void jButtonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetourMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButtonRetourMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edition;
    private javax.swing.JLabel NomRallye;
    private javax.swing.JLabel dateDebut;
    private javax.swing.JLabel dateFin;
    private javax.swing.JLabel dateN;
    private javax.swing.JLabel idVehicule;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValiderIns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGroupeSanguin;
    private javax.swing.JLabel jLabelNomVehicule;
    private javax.swing.JLabel jLabelSysdate;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBooleanRh;
    private javax.swing.JLabel lieu;
    private javax.swing.JLabel nomCoureur;
    private javax.swing.JLabel prenomCoureur;
    private javax.swing.JLabel vehicule;
    private javax.swing.JLabel vehiculeA;
    private javax.swing.JLabel vehiculeP;
    // End of variables declaration//GEN-END:variables
}
