/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import dataTools.DataReader;
import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import FFRAG.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 21611929
 */
public class Organisateur_Classement extends javax.swing.JFrame {
    private Model_F mf;
    /**
     * Creates new form Classement
     */
    public Organisateur_Classement() throws ParseException {
        initComponents();
        mf = new Model_F();
        for(Rallye r : mf.getListRallye()){
            this.jComboBoxChoisirRallye.addItem(r.getNom());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxChoisirRallye = new javax.swing.JComboBox<>();
        jButtonRetour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableC = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxEdition = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxEtape = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Classements");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Choisir Rallye");

        jComboBoxChoisirRallye.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxChoisirRallyeItemStateChanged(evt);
            }
        });
        jComboBoxChoisirRallye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxChoisirRallyeMouseClicked(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRetourMouseClicked(evt);
            }
        });

        jTableC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ordre", "Nom", "Prenom", "Temps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableC.setName(""); // NOI18N
        jTableC.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTableC);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Choisir Edition :");

        jComboBoxEdition.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEditionItemStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Choisir Etape :");

        jComboBoxEtape.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEtapeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxChoisirRallye, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxEtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButtonRetour))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxChoisirRallye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jComboBoxEtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButtonRetour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetourMouseClicked
        // TODO add your handling code here:
         this.dispose();
        Organisateur_MenuPrincipale mp = new Organisateur_MenuPrincipale();
        mp.setVisible(true);
    }//GEN-LAST:event_jButtonRetourMouseClicked

    private void jComboBoxChoisirRallyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxChoisirRallyeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxChoisirRallyeMouseClicked

    private void jComboBoxChoisirRallyeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxChoisirRallyeItemStateChanged
       SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        //chercher rallye
        this.jComboBoxEdition.removeAllItems();
        this.jTableC.removeAll();
        
        if(this.jComboBoxChoisirRallye.getSelectedItem()!=null){
            try {
                for(Rallye rallye : mf.getListRallye()){
                    if(this.jComboBoxChoisirRallye.getSelectedItem().equals(rallye.getNom())){
                        for(Edition e : rallye.getListEdition()){
                            this.jComboBoxEdition.addItem(df.format(e.getDateDeb()));
                        }
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
            
    }//GEN-LAST:event_jComboBoxChoisirRallyeItemStateChanged

    private void jComboBoxEtapeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEtapeItemStateChanged
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        this.jTableC.removeAll();
        if(this.jComboBoxEtape.getSelectedItem()!=null){
            if(this.jComboBoxEdition.getSelectedItem()!=null){
                
                //calculer le temps
                try {
                    for(Rallye r : mf.getListRallye()){
                        if(this.jComboBoxChoisirRallye.getSelectedItem().equals(r.getNom())){
                            for(Edition e : r.getListEdition()){
                                if(this.jComboBoxEdition.getSelectedItem().equals(df.format(e.getDateDeb()))){
                                    for(Etape eta : e.getListEtape()){
                                        if(this.jComboBoxEtape.getSelectedItem().equals(String.valueOf(eta.getCodeE()))){
                                            for(Participant p : eta.getEdition().getListParticipant()){
                                                p.calculeTempsFinal();
                                            }

                                            eta.calculerClassement();
                                            eta.validerClassement();

                                            DefaultTableModel tm = (DefaultTableModel) this.jTableC.getModel();
                                            tm.setNumRows(0);

                                            for(Integer c : eta.getClassement().keySet()){
                                                tm.addRow(new Object[]{c,eta.getClassement().get(c).getParticipant().getCoureur().getNom(),eta.getClassement().get(c).getParticipant().getCoureur().getPrenom(),eta.getClassement().get(c).getParticipant().getTempsFinal()});
                                            }
                                            break;
                                        }

                                    }
                                }
                            }
                        }
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jComboBoxEtapeItemStateChanged

    private void jComboBoxEditionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEditionItemStateChanged
        // TODO add your handling code here:
        this.jComboBoxEtape.removeAllItems();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");

        if(this.jComboBoxEdition.getSelectedItem()!=null){
            try {
                for(Rallye rallye : mf.getListRallye()){
                    if(this.jComboBoxChoisirRallye.getSelectedItem().equals(rallye.getNom())){
                        for(Edition e : rallye.getListEdition()){
                            if(this.jComboBoxEdition.getSelectedItem().equals(df.format(e.getDateDeb()))){
                                for(Etape eta : e.getListEtape()){
                                    this.jComboBoxEtape.addItem(String.valueOf(eta.getCodeE()));
                                }
                            }
                        }
                    }
                }   } catch (ParseException ex) {
                    Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jComboBoxEditionItemStateChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JComboBox<String> jComboBoxChoisirRallye;
    private javax.swing.JComboBox<String> jComboBoxEdition;
    private javax.swing.JComboBox<String> jComboBoxEtape;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableC;
    // End of variables declaration//GEN-END:variables
}
