/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import dataTools.DataReader;
import java.io.File;
import java.util.ArrayList;


/**
 *
 * @author jy
 */
public class Organisateur_InscriptionParticipant extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    public Organisateur_InscriptionParticipant() {
        initComponents();
        this.puissanceV.setEnabled(false);
        this.PoidsC.setEnabled(false);
        
        DataReader dr=new DataReader();
        File file = new File ("src/csv/Rallye.csv");
        ArrayList<String> list = new ArrayList<String>();

        ArrayList<String[]> res2 = dr.getTable1(file);
        for(String[] tab :res2){
            if(!list.contains(tab[0])){
                list.add(tab[0]);
            }
        }
        
        for(int i=0; i< list.size()-1;i++){
            this.jComboBoxRallye.addItem(list.get(i));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTypeVehicule = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxRallye = new javax.swing.JComboBox<>();
        jLabellieu = new javax.swing.JLabel();
        Edition = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IdVehicule = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PrenomCoureurIns = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NomCoureurIns1 = new javax.swing.JTextField();
        jRadioButtonVoiture = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        puissanceV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PoidsC = new javax.swing.JTextField();
        dateDebut = new javax.swing.JLabel();
        dateFin = new javax.swing.JLabel();
        jButtonValiderIns = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        NomVehicule = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxGroupeSanguin = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        DateNaissance = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Inscription");

        jLabel2.setText("Nom du Rallye");

        jComboBoxRallye.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRallyeItemStateChanged(evt);
            }
        });
        jComboBoxRallye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxRallyeMouseClicked(evt);
            }
        });

        jLabellieu.setText("Lieu");

        Edition.setText("Edition la plus nouvelle");

        jLabel5.setText("Edition");

        jLabel6.setText("dateFin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Coureur");

        jLabel8.setText("Nom");

        IdVehicule.setText(" ");
        IdVehicule.setName("nomCoureur"); // NOI18N
        IdVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdVehiculeActionPerformed(evt);
            }
        });

        jLabel9.setText("Prenom");

        PrenomCoureurIns.setText(" ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Véhicule");

        jLabel12.setText("Numéro Immatriculation du véhicule");

        NomCoureurIns1.setText(" ");
        NomCoureurIns1.setName("nomCoureur"); // NOI18N
        NomCoureurIns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomCoureurIns1ActionPerformed(evt);
            }
        });

        buttonGroupTypeVehicule.add(jRadioButtonVoiture);
        jRadioButtonVoiture.setText("Voiture");
        jRadioButtonVoiture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonVoitureMouseClicked(evt);
            }
        });
        jRadioButtonVoiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVoitureActionPerformed(evt);
            }
        });

        jLabel13.setText("Puissance");

        puissanceV.setText(" ");
        puissanceV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puissanceVActionPerformed(evt);
            }
        });

        jLabel14.setText("Poids");

        PoidsC.setText(" ");

        dateDebut.setText("dateDebutAfficher");

        dateFin.setText("dateFinAfficher");

        jButtonValiderIns.setText("Valider");
        jButtonValiderIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValiderInsMouseClicked(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnnulerMouseClicked(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRetourMouseClicked(evt);
            }
        });

        jLabel15.setText("dateDebut");

        NomVehicule.setText(" ");
        NomVehicule.setName("nomCoureur"); // NOI18N
        NomVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomVehiculeActionPerformed(evt);
            }
        });

        jLabel16.setText("NomVehicule");

        jLabel17.setText("Niveau Experience");

        jComboBoxGroupeSanguin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "expert", "junior", "debutant" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Rallye");

        jLabel20.setText("DateNaissance");

        DateNaissance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxRallye, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabellieu)
                            .addComponent(jLabel15)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateFin)
                            .addComponent(dateDebut)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Edition)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NomCoureurIns1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxGroupeSanguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PrenomCoureurIns, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(32, 32, 32)
                            .addComponent(NomVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IdVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(191, 191, 191))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonVoiture)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(puissanceV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PoidsC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonRetour)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButtonValiderIns)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonAnnuler)))
                                .addGap(93, 93, 93))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxRallye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellieu)
                    .addComponent(jLabel5)
                    .addComponent(Edition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dateDebut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(PrenomCoureurIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(NomCoureurIns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(DateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxGroupeSanguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(IdVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(NomVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(PoidsC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonVoiture)
                    .addComponent(jLabel13)
                    .addComponent(puissanceV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValiderIns)
                    .addComponent(jButtonAnnuler)
                    .addComponent(jButtonRetour))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdVehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdVehiculeActionPerformed

    private void NomCoureurIns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomCoureurIns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomCoureurIns1ActionPerformed

    private void puissanceVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puissanceVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puissanceVActionPerformed

    private void jRadioButtonVoitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVoitureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVoitureActionPerformed

    private void jButtonAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnnulerMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerMouseClicked

    private void jButtonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetourMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Organisateur_MenuPrincipale mp = new Organisateur_MenuPrincipale();
        mp.setVisible(true);
    }//GEN-LAST:event_jButtonRetourMouseClicked

    private void jComboBoxRallyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxRallyeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxRallyeMouseClicked

    private void jButtonValiderInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderInsMouseClicked
        // TODO add your handling code here:
        Organisateur_InscriptionValide iv = new Organisateur_InscriptionValide(this.jComboBoxRallye.getSelectedItem().toString(),this.jLabellieu.getText(),
            this.Edition.getText(),this.dateDebut.getText(),this.dateFin.getText(),this.NomCoureurIns1.getText(),this.PrenomCoureurIns.getText(),
            this.DateNaissance.getText(),this.jComboBoxGroupeSanguin.getSelectedItem().toString(),this.jComboBoxGroupeSanguin.getSelectedItem().toString(),this.NomVehicule.getText(),this.IdVehicule.getText(), this.jRadioButtonVoiture.isSelected(),this.puissanceV.getText(),this.PoidsC.getText());
        iv.setVisible(true);
    }//GEN-LAST:event_jButtonValiderInsMouseClicked

    private void jRadioButtonVoitureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonVoitureMouseClicked
        // TODO add your handling code here:
        this.puissanceV.setEnabled(true);
        this.PoidsC.setEnabled(false);
        this.PoidsC.setText("");
    }//GEN-LAST:event_jRadioButtonVoitureMouseClicked

    private void jComboBoxRallyeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRallyeItemStateChanged
        // TODO add your handling code here:
        DataReader dr=new DataReader();
        File file = new File ("src/CSV/Rallye.csv");
        ArrayList<String> list = new ArrayList<String>();
       
        ArrayList<String[]> res2 = dr.getTable1(file);
        for(String[] tab :res2){
            if(tab[0]!=null){
                if(this.jComboBoxRallye.getSelectedItem().equals(tab[0]) ){
                    this.jLabellieu.setText(tab[1]);
                    this.Edition.setText(tab[2]);
                }
                
            }
        }
        //this.jLabellieu.setText(res[this.jComboBoxRallye.getSelectedIndex()+1][1]);
        //this.Edition.setText(res[this.jComboBoxRallye.getSelectedIndex()+1][2]);
        
        File fileEdition = new File("src/CSV/Edition.csv");
        ArrayList<String[]> res3 = dr.getTable1(fileEdition);
        for(String[] tab :res3){
            if(tab[0]!=null){
                
                if(this.jComboBoxRallye.getSelectedItem().equals(tab[1]) && this.Edition.getText().equals(tab[0]) ){
                    this.dateDebut.setText(tab[2]);
                    this.dateFin.setText(tab[3]);
                }
                
            }
           
        }
        
    }//GEN-LAST:event_jComboBoxRallyeItemStateChanged

    private void NomVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomVehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomVehiculeActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DateNaissance;
    private javax.swing.JLabel Edition;
    private javax.swing.JTextField IdVehicule;
    private javax.swing.JTextField NomCoureurIns1;
    private javax.swing.JTextField NomVehicule;
    private javax.swing.JTextField PoidsC;
    private javax.swing.JTextField PrenomCoureurIns;
    private javax.swing.ButtonGroup buttonGroupTypeVehicule;
    private javax.swing.JLabel dateDebut;
    private javax.swing.JLabel dateFin;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValiderIns;
    private javax.swing.JComboBox<String> jComboBoxGroupeSanguin;
    private javax.swing.JComboBox<String> jComboBoxRallye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabellieu;
    private javax.swing.JRadioButton jRadioButtonVoiture;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField puissanceV;
    // End of variables declaration//GEN-END:variables
}
