/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 21611929
 */
public class Organisateur_MenuPrincipale extends javax.swing.JFrame {
    /**
     * Creates new form MenuPrincipale
     */
    public Organisateur_MenuPrincipale() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonMenuCreerEdition = new javax.swing.JButton();
        jButtonMenuClassement = new javax.swing.JButton();
        jButtonMenuInscription = new javax.swing.JButton();
        jButtonValiderRallye2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Menu Principale Organisateur");

        jButtonMenuCreerEdition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMenuCreerEdition.setText("Créer Rallye/Edition");
        jButtonMenuCreerEdition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenuCreerEditionMouseClicked(evt);
            }
        });

        jButtonMenuClassement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMenuClassement.setText("Consulter Classement");
        jButtonMenuClassement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenuClassementMouseClicked(evt);
            }
        });

        jButtonMenuInscription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMenuInscription.setText("Enregistrer Inscription");
        jButtonMenuInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenuInscriptionMouseClicked(evt);
            }
        });

        jButtonValiderRallye2.setText("Retour");
        jButtonValiderRallye2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValiderRallye2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonValiderRallye2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonMenuInscription, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(jButtonMenuClassement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMenuCreerEdition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel2)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButtonMenuCreerEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonMenuInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonMenuClassement, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonValiderRallye2)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2)
                    .addContainerGap(388, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuCreerEditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuCreerEditionMouseClicked
    
        try {
            // TODO add your handling code here:
            this.dispose();
            Organisateur_Rallye_1 edition = new Organisateur_Rallye_1();
            edition.setVisible(true);
            edition.setLocationRelativeTo(null);
        } catch (ParseException ex) {
            Logger.getLogger(Organisateur_MenuPrincipale.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_jButtonMenuCreerEditionMouseClicked

    private void jButtonMenuInscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuInscriptionMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Organisateur_InscriptionParticipant inscription = new Organisateur_InscriptionParticipant();
        inscription.setVisible(true);
        inscription.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButtonMenuInscriptionMouseClicked

    private void jButtonMenuClassementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuClassementMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Organisateur_Classement classement = new Organisateur_Classement();
        classement.setVisible(true);
        classement.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonMenuClassementMouseClicked

    private void jButtonValiderRallye2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderRallye2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Accueil a = new Accueil();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonValiderRallye2MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuClassement;
    private javax.swing.JButton jButtonMenuCreerEdition;
    private javax.swing.JButton jButtonMenuInscription;
    private javax.swing.JButton jButtonValiderRallye2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
