/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import FFRAG.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;

/**
 *
 * @author 21611929
 */
public class Organisateur_Rallye_2 extends javax.swing.JFrame {
    private Model_F mf;
    private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form Rallye
     */
    public Organisateur_Rallye_2(String rallye, String lieu) throws ParseException {
        initComponents();
        this.jLabelRallye.setText(rallye);
        this.jLabelLieu.setText(lieu);
        mf = new Model_F();
        this.jButtonValiderRallye.setEnabled(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroupAjouterEtape = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEtape = new javax.swing.JTable();
        jButtonValiderRallye = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelDistance = new javax.swing.JFormattedTextField();
        jLabelNombreVirage = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonAjouterEtapeNouvelle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelRallye = new javax.swing.JLabel();
        jLabelLieu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserDebut = new com.toedter.calendar.JDateChooser();
        jDateChooserFin = new com.toedter.calendar.JDateChooser();

        jLabel5.setText("dateDebut");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEtape.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ordre", "Distance", "NombreVirage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEtape.setName(""); // NOI18N
        jTableEtape.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTableEtape);

        jButtonValiderRallye.setText("Valider");
        jButtonValiderRallye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValiderRallyeMouseClicked(evt);
            }
        });

        jLabel7.setText("dateFin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ajouter Etape");

        jButtonRetour.setText("Retour");
        jButtonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRetourMouseClicked(evt);
            }
        });

        jLabel9.setText("saisir nombres");

        jButtonAjouterEtapeNouvelle.setText("+");
        jButtonAjouterEtapeNouvelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAjouterEtapeNouvelleMouseClicked(evt);
            }
        });
        jButtonAjouterEtapeNouvelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterEtapeNouvelleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ajouter Edition");

        jLabel6.setText("dateDebut");

        jLabel1.setText("Rallye : ");

        jLabel2.setText("Lieu :");

        jLabelRallye.setText("jLabel8");

        jLabelLieu.setText("jLabel10");

        jLabel8.setText("distance");

        jLabel10.setText("nombre de virage");

        jDateChooserDebut.setDateFormatString("dd/MM/yyyy");
        jDateChooserDebut.setMinSelectableDate(new java.util.Date(-1577919521000L));

        jDateChooserFin.setDateFormatString("dd/MM/yyyy");
        jDateChooserFin.setMinSelectableDate(new java.util.Date(-1577919521000L));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addComponent(jLabelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRallye)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelLieu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNombreVirage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(99, 99, 99)
                                .addComponent(jButtonAjouterEtapeNouvelle)))
                        .addContainerGap(47, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(jButtonRetour)
                    .addGap(28, 28, 28)
                    .addComponent(jButtonValiderRallye)
                    .addContainerGap(533, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabelRallye)
                        .addComponent(jLabelLieu)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jDateChooserDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabelNombreVirage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButtonAjouterEtapeNouvelle)))
                .addGap(2, 2, 2)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(448, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonValiderRallye)
                        .addComponent(jButtonRetour))
                    .addGap(26, 26, 26)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderRallyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderRallyeMouseClicked
    
        if(this.jDateChooserDebut.getDate().compareTo(this.jDateChooserFin.getDate()) == 1||this.jDateChooserDebut.getDate().compareTo(this.jDateChooserFin.getDate()) == 0){
            JOptionPane.showMessageDialog(null, "datedeb doit superieur a datefin", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                //recuperer les dates 
                Calendar now = Calendar.getInstance();
                Calendar dob = Calendar.getInstance();

                dob.setTime(jDateChooserDebut.getDate());
                int day = dob.get(Calendar.DAY_OF_MONTH);
                String jour = String.format("%02d", day); 
                int month = dob.get(Calendar.MONTH)+1;
                String mois = String.format("%02d", month); 
                int year = dob.get(Calendar.YEAR);
                String DateDebut = jour+"/"+mois+"/"+year;

                now.setTime(jDateChooserFin.getDate());
                int dayF = now.get(Calendar.DAY_OF_MONTH);
                String jourF = String.format("%02d", dayF); 
                int monthF = now.get(Calendar.MONTH)+1;
                String moisF = String.format("%02d", monthF); 
                int yearF = now.get(Calendar.YEAR);

                String DateFin = jourF+"/"+moisF+"/"+yearF;
                
                boolean trouver = false;
                //enregistrer rallye
                for(Rallye r : this.mf.getListRallye()){
                    if(this.jLabelRallye.getText().equals(r.getNom())){
                        trouver = true;
                        //enregistrer edition 
                        for(Edition e : r.getListEdition()){
                            if(DateDebut.equals(df.format(e.getDateDeb()))){
                                JOptionPane.showMessageDialog(null, "meme datedeb de ce rallye deja exist", "Error", JOptionPane.ERROR_MESSAGE);
                                break;
                            }else{
                                mf.enregistrerEdition(this.jLabelRallye.getText(), DateDebut, DateFin);
                                //enregistrer etape
                                int nbR = this.jTableEtape.getRowCount();
                                for (int i = 0;i<nbR;i++){   
                                    mf.enregistrerEtape(this.jLabelRallye.getText(), DateDebut, this.jTableEtape.getValueAt(i, 0).toString(), this.jTableEtape.getValueAt(i, 1).toString(), this.jTableEtape.getValueAt(i, 2).toString());
                                }
                                JOptionPane.showConfirmDialog(null, "bien enregistre", "infos", JOptionPane.OK_OPTION);
                                this.dispose();
                                break;
                            }
                        }
                    }
                }
                    
                if(trouver == false){
                        this.mf.enregistrerRallye(this.jLabelRallye.getText(), this.jLabelLieu.getText());
                        mf.enregistrerEdition(this.jLabelRallye.getText(), DateDebut, DateFin);
                        //enregistrer etape
                        int nbR = this.jTableEtape.getRowCount();
                        for (int i = 0;i<nbR;i++){   
                            mf.enregistrerEtape(this.jLabelRallye.getText(), DateDebut, this.jTableEtape.getValueAt(i, 0).toString(), this.jTableEtape.getValueAt(i, 1).toString(), this.jTableEtape.getValueAt(i, 2).toString());
                        }
                        JOptionPane.showConfirmDialog(null, "bien enregistre", "infos", JOptionPane.OK_OPTION);
                        
                }
            } catch (ParseException ex) {
                Logger.getLogger(Organisateur_Rallye_2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonValiderRallyeMouseClicked

    private void jButtonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetourMouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            Organisateur_Rallye_1 OR1 = new Organisateur_Rallye_1();
            OR1.setVisible(true);
            OR1.setLocationRelativeTo(null);
        } catch (ParseException ex) {
            Logger.getLogger(Organisateur_Rallye_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRetourMouseClicked

    private void jButtonAjouterEtapeNouvelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAjouterEtapeNouvelleMouseClicked
        // ajouter une etape dans la table
        if(this.jLabelDistance.getText().isEmpty()||this.jLabelDistance.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Il faut saisir des nombres", "OK", JOptionPane.OK_OPTION);
        }else{
            String[] listdata = {"1",this.jLabelDistance.getText(),this.jLabelDistance.getText()};
            DefaultTableModel m = (DefaultTableModel) this.jTableEtape.getModel();
            int r = this.jTableEtape.getRowCount();
            m.addRow(new Object[]{r+1,this.jLabelDistance.getText(),this.jLabelNombreVirage.getText()});
            
            this.jButtonValiderRallye.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButtonAjouterEtapeNouvelleMouseClicked

    private void jButtonAjouterEtapeNouvelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterEtapeNouvelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjouterEtapeNouvelleActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAjouterEtape;
    private javax.swing.JButton jButtonAjouterEtapeNouvelle;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValiderRallye;
    private com.toedter.calendar.JDateChooser jDateChooserDebut;
    private com.toedter.calendar.JDateChooser jDateChooserFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField jLabelDistance;
    private javax.swing.JLabel jLabelLieu;
    private javax.swing.JFormattedTextField jLabelNombreVirage;
    private javax.swing.JLabel jLabelRallye;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEtape;
    // End of variables declaration//GEN-END:variables
}
