/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import FFRAG.*;
import dataTools.DataReader;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import dataTools.DataWriter;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 21611924
 */
public class Parieur_MonCompte extends javax.swing.JFrame {
        private Model_F mf;
        private String niveau;
        private int nbVirage;
        private float puissance;
        private float poids;
        private float distance;
        
    /**
     * Creates new form CompteParieur
     * @param email
     * @throws java.text.ParseException
     */
    public Parieur_MonCompte(String email) throws ParseException {
        initComponents();
        this.setVisible(true);
        this.setSize(810,547);
        this.setLocationRelativeTo(null);
        mf = new Model_F();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        this.jLabelEmail1.setText(email);
        //this.jTabbedPane1.setOpaque(true);
        
        DefaultTableModel tm = (DefaultTableModel) this.jTable1.getModel();
        tm.setNumRows(0);
        
        for(Parieur parieur:mf.getListParieur()){
            if(parieur.getEmail().equals(email)){
                for(Parier parier : parieur.getListeParier()){
                    String etat = "";
                    String gain = "";
                    if(parier.getEtapeFini()){
                        System.out.print(parier.getEtapeFini());
                        etat = "Fini";
                        gain = String.valueOf(parier.getGain());
                    }else{
                        etat = "En cours";
                        gain = "0";
                    }
                    tm.addRow(new Object[]{parier.getEtape().getEdition().getRallye().getNom(),df.format(parier.getEtape().getEdition().getDateDeb()),parier.getEtape().getCodeE(),parier.getPilote(),parier.getMise(),parier.getCote(),gain,etat});
                }
            }
        }
        
        // recuperer les infos de tous les coureurs dans la combobox
        for(Coureur c : this.mf.getListCoureur()){
            this.jComboBoxParticipant.addItem(c.toString());            
        }
        
        // recuperer les vehicules dans la combobox
        for(Vehicule v : this.mf.getListVehicule()){
            this.jComboBoxVehicule.addItem(v.getNom());
        }
        
        // recuperer les rallyes dans la combobox
        for(int i = 0; i<this.mf.getListRallye().size();i++){
            this.jComboBoxRallye.addItem(this.mf.getListRallye().get(i).getNom());
            this.jCBRallye.addItem(this.mf.getListRallye().get(i).getNom());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCotation = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jBtnParier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelEditionNouvelle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBRallye = new javax.swing.JComboBox<>();
        jLabelDistance = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBEtape = new javax.swing.JComboBox<>();
        jLabelNbV = new javax.swing.JLabel();
        jTextMise = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxParticipant = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxRallye = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxEtape = new javax.swing.JComboBox<>();
        jButtonSimuler = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabelNiveauExp = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelPuissance = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelPoids = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelDistanceSimuler = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelNbVirage = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelTempsProbableMin = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxVehicule = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxEdition = new javax.swing.JComboBox<>();
        jLabelTempsProbableMax = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableCotation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Participant", "Cotation"
            }
        ));
        jScrollPane2.setViewportView(jTableCotation);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mise : ");

        jBtnParier.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jBtnParier.setText("Parier");
        jBtnParier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnParierMouseClicked(evt);
            }
        });

        jLabel4.setText("Edition la plus nouvelle : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tous les paris disponbiles");

        jLabelEditionNouvelle.setText(" ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Rallye : ");

        jLabel9.setText("Distance : ");

        jCBRallye.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBRallyeItemStateChanged(evt);
            }
        });

        jLabelDistance.setText(" ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Etape : ");

        jLabel11.setText("Nombre de virage : ");

        jCBEtape.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBEtapeItemStateChanged(evt);
            }
        });

        jLabelNbV.setText(" ");

        jTextMise.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTextMise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEtape, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNbV, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBRallye, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEditionNouvelle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jBtnParier))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel12))
                            .addComponent(jTextMise, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBRallye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEditionNouvelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCBEtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelDistance)
                    .addComponent(jLabel11)
                    .addComponent(jLabelNbV))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBtnParier)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Faire Pari", jPanel2);

        jLabel8.setText("Choisir Participants :");

        jComboBoxParticipant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxParticipantItemStateChanged(evt);
            }
        });

        jLabel13.setText("Choisir Rallye :");

        jComboBoxRallye.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRallyeItemStateChanged(evt);
            }
        });

        jLabel14.setText("Choisir Etape :");

        jComboBoxEtape.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEtapeItemStateChanged(evt);
            }
        });

        jButtonSimuler.setText("Simuler le temps probable");
        jButtonSimuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSimulerMouseClicked(evt);
            }
        });

        jLabel15.setText("Niveau Experience : ");

        jLabelNiveauExp.setText("Niveau Experience");

        jLabel17.setText("Puissance :");

        jLabelPuissance.setText("Puissance:");

        jLabel18.setText("Poids :");

        jLabelPoids.setText("Poids");

        jLabel21.setText("Distance :");

        jLabelDistanceSimuler.setText("Distance :");

        jLabel22.setText("Nb Virage :");

        jLabelNbVirage.setText("Nb Virage :");

        jLabel23.setText("TempsProbable : ");

        jLabelTempsProbableMin.setText("TempsProbable");

        jLabel25.setText("Choisir Vehicule :");

        jComboBoxVehicule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxVehiculeItemStateChanged(evt);
            }
        });

        jLabel26.setText("Choisir Edition :");

        jComboBoxEdition.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEditionItemStateChanged(evt);
            }
        });

        jLabelTempsProbableMax.setText("TempsProbable");

        jLabel24.setText("~~");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRallye, 0, 143, Short.MAX_VALUE)
                            .addComponent(jComboBoxParticipant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxEtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButtonSimuler, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNiveauExp)
                            .addComponent(jLabelPuissance)
                            .addComponent(jLabelPoids)
                            .addComponent(jLabelNbVirage)
                            .addComponent(jLabelDistanceSimuler)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelTempsProbableMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTempsProbableMax)))
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jComboBoxVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBoxRallye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBoxEtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonSimuler)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabelNiveauExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabelPuissance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelPoids))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabelDistanceSimuler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabelNbVirage))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabelTempsProbableMin)
                    .addComponent(jLabelTempsProbableMax)
                    .addComponent(jLabel24))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulter Participant", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vos Mises Historiques");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rallye", "Edition", "Etape", "Participant", "Mise", "Cote", "Gain", "Etat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulter Mises", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 74, 767, 370);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Compte : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 20, 90, 17);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/icons8-connexion-64.png"))); // NOI18N
        jButton2.setText("Deconnexion");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 20, 210, 39);

        jLabelEmail1.setText("123@gmail.com");
        getContentPane().add(jLabelEmail1);
        jLabelEmail1.setBounds(120, 20, 290, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/NG2015_020215_091225_RB-820x547.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 1, 820, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    try {
        // TODO add your handling code here:
        this.dispose();
        Parieur_Inscription ip = new Parieur_Inscription();
        ip.setVisible(true);
    } catch (ParseException ex) {
        Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jComboBoxRallyeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRallyeItemStateChanged
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        //chercher rallye
        this.jComboBoxEdition.removeAllItems();
        
        if(this.jComboBoxRallye.getSelectedItem()!=null){
            try {
                for(Rallye rallye : mf.getListRallye()){
                    if(this.jComboBoxRallye.getSelectedItem().equals(rallye.getNom())){
                        for(Edition e : rallye.getListEdition()){
                            this.jComboBoxEdition.addItem(df.format(e.getDateDeb()));
                        }
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
            
           
    }//GEN-LAST:event_jComboBoxRallyeItemStateChanged

    private void jComboBoxEditionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEditionItemStateChanged
        // TODO add your handling code here:
        this.jComboBoxEtape.removeAllItems();
         SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
         
         if(this.jComboBoxEdition.getSelectedItem()!=null){
            try {
                for(Rallye rallye : mf.getListRallye()){
                    if(this.jComboBoxRallye.getSelectedItem().equals(rallye.getNom())){
                        for(Edition e : rallye.getListEdition()){
                            if(this.jComboBoxEdition.getSelectedItem().equals(df.format(e.getDateDeb()))){
                                for(Etape eta : e.getListEtape()){           
                                    this.jComboBoxEtape.addItem(String.valueOf(eta.getCodeE()));
                                }
                            }
                        }
                    }
                }   } catch (ParseException ex) {
                Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_jComboBoxEditionItemStateChanged

    private void jComboBoxEtapeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEtapeItemStateChanged
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        if(this.jCBEtape.getSelectedItem()!=null){
            if(this.jComboBoxEdition.getSelectedItem()!=null){
            
            //calculer le temps
             try {
                 for(Rallye r : mf.getListRallye()){
                     if(this.jComboBoxRallye.getSelectedItem().equals(r.getNom())){
                         for(Edition e : r.getListEdition()){
                             if(this.jComboBoxEdition.getSelectedItem().equals(df.format(e.getDateDeb()))){
                                 for(Etape eta : e.getListEtape()){
                                     if(this.jComboBoxEtape.getSelectedItem().equals(String.valueOf(eta.getCodeE()))){
                                         
                                        this.jLabelDistanceSimuler.setText(String.valueOf(eta.getDistance()));
                                        this.jLabelNbVirage.setText(String.valueOf(eta.getNbVirage()));
                                        
                                        nbVirage = eta.getNbVirage();
                                        distance =eta.getDistance();
                                         
                                     }
                                     
                                 }
                             } 
                         }
                     }
                 } 
                 } catch (ParseException ex) {
                 Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
             }

        }
        }
    }//GEN-LAST:event_jComboBoxEtapeItemStateChanged

    private void jButtonSimulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimulerMouseClicked
        // TODO add your handling code here:
        float coefNiveau;
        switch (niveau) {
                case "expert":
                    coefNiveau = (float)3.399;
                    break;
                case "junior":
                    coefNiveau = (float)0.63;
                    break;
                default:
                    coefNiveau = 0;
                    break;
            }
        float vitesse = (float)(50.441+coefNiveau + 1.7155*this.poids*0.001+0.0143*this.puissance-0.0072*this.nbVirage);
        float temps = (float) this.distance/vitesse;
        
        String tmin = mf.transformerHeure(String.valueOf(temps*50/60));
        String tmax = mf.transformerHeure(String.valueOf(temps*70/60));
        
       this.jLabelTempsProbableMin.setText(tmin);
       this.jLabelTempsProbableMax.setText(tmax);
       
       
        
    }//GEN-LAST:event_jButtonSimulerMouseClicked

    private void jComboBoxParticipantItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxParticipantItemStateChanged
        // TODO add your handling code here:
        for(Coureur c: mf.getListCoureur()){
            if(this.jComboBoxParticipant.getSelectedItem().equals(c.toString())){
                this.jLabelNiveauExp.setText(c.getNiveau());
                 niveau = c.getNiveau();
            }
        }
    }//GEN-LAST:event_jComboBoxParticipantItemStateChanged

    private void jComboBoxVehiculeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxVehiculeItemStateChanged
        // TODO add your handling code here:
        for(Vehicule v: mf.getListVehicule()){
            if(this.jComboBoxVehicule.getSelectedItem().equals(v.getNom())){
                this.jLabelPoids.setText(String.valueOf(v.getPoids()));
                this.jLabelPuissance.setText(String.valueOf(v.getPuissance()));
                puissance =v.getPuissance();
                poids = v.getPoids();
            }
        }
    }//GEN-LAST:event_jComboBoxVehiculeItemStateChanged

    private void jTextMiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMiseActionPerformed

    private void jCBEtapeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBEtapeItemStateChanged
        // TODO add your handling code here:
        // chercher la liste des étapes de l'édition la plus nouvelle du rallye selectioné
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        if(this.jCBEtape.getSelectedItem()!=null){
            this.jTableCotation.removeAll();
            File fileTP = new File ("src/CSV/TempsProbable.csv");
            DataReader dr = new DataReader();
            DataWriter dw = new DataWriter();
            try {
                dw.clearCsv(fileTP, true);
            } catch (Exception ex) {
                Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
            //ajouter les donnees
            try {
                for(Rallye r : mf.getListRallye()){
                    if(this.jCBRallye.getSelectedItem().equals(r.getNom())){
                        for(Edition e : r.getListEdition()){
                            if(this.jLabelEditionNouvelle.getText().equals(df.format(e.getDateDeb()))){
                                for(Etape eta : e.getListEtape()){
                                    if(this.jCBEtape.getSelectedItem().equals(String.valueOf(eta.getCodeE()))){

                                        this.jLabelDistance.setText(String.valueOf(eta.getDistance()));
                                        this.jLabelNbV.setText(String.valueOf(eta.getNbVirage()));
                                        eta.getClassementProbable();
                                        eta.cotation();

                                        DefaultTableModel tm = (DefaultTableModel) this.jTableCotation.getModel();
                                        tm.setNumRows(0);

                                        for(Coureur c : eta.getCotation().keySet()){
                                            tm.addRow(new Object[]{c.toString(),eta.getCotation().get(c)});
                                        }
                                    }

                                }
                            }

                        }
                    }

                }} catch (ParseException ex) {
                    Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
                }

                //add donnees dans le table
                //DefaultTableModel tm = (DefaultTableModel) this.jTableCotation.getModel();
                //tm.setNumRows(0);

                //ArrayList<String[]> resC =dr.getTable1(fileTP);

                //for(String[] tab :resC){
                    //  if(tab[0]!=null){
                        //if(this.jCBRallye.getSelectedItem().equals(resC[i][2])&&this.jLabelEditionNouvelle.getText().equals(resC[i][3])&&this.jCBEtape.getSelectedItem().equals(resC[i][4])){
                            //        tm.addRow(new Object[]{tab[0],tab[1]});
                            //}
                        //}
                    //}

            }
    }//GEN-LAST:event_jCBEtapeItemStateChanged

    private void jCBRallyeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBRallyeItemStateChanged
        // TODO add your handling code here:

        ArrayList<Date> list2 = new ArrayList<Date>();

        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        //chercher rallye
        if(this.jCBRallye.getSelectedItem()!=null){
            try {
                for(Rallye rallye : mf.getListRallye()){
                    if(this.jCBRallye.getSelectedItem().equals(rallye.getNom())){
                        for(Edition e : rallye.getListEdition()){
                            list2.add(e.getDateDeb());
                        }
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
            //trouver l'edition plus nouvelle
            if(!list2.isEmpty()){
                Date max = list2.get(0);
                for(int i = 0; i<list2.size();i++){
                    int r = max.compareTo(list2.get(i));

                    if (r == -1){
                        max = list2.get(i);
                    }
                }

                // afficher la date de l'édition la plus nouvelle
                this.jLabelEditionNouvelle.setText(df.format(max));
                this.jCBEtape.removeAllItems();
                this.jTableCotation.removeAll();
                try {
                    // chercher la liste des étapes de l'édition la plus nouvelle du rallye selectioné
                    for(Rallye rallye : mf.getListRallye()){
                        if(this.jCBRallye.getSelectedItem().equals(rallye.getNom())){
                            for(Edition e : rallye.getListEdition()){
                                if(df.format(max).equals(df.format(e.getDateDeb()))){
                                    for(Etape eta : e.getListEtape()){
                                        this.jCBEtape.addItem(String.valueOf(eta.getCodeE()));
                                        this.jLabelDistance.setText(String.valueOf(eta.getDistance()));
                                        this.jLabelNbV.setText(String.valueOf(eta.getNbVirage()));
                                    }
                                }

                            }
                        }
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jCBRallyeItemStateChanged

    private void jBtnParierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnParierMouseClicked
        // TODO add your handling code here:

        String email = this.jLabelEmail1.getText();
        String nomRallye = String.valueOf(this.jCBRallye.getSelectedItem());
        String Datedeb = this.jLabelEditionNouvelle.getText();
        String codeEtape = String.valueOf(this.jCBEtape.getSelectedItem());
        String mise = this.jTextMise.getText();

        int i = this.jTableCotation.getSelectedRow();

        if(i>0 &&mise != ""){
            String pilote = String.valueOf(this.jTableCotation.getValueAt(i, 0));
            String cote = String.valueOf(this.jTableCotation.getValueAt(i, 1));
            mf.enregistrerParier(email,pilote,nomRallye,Datedeb,codeEtape,mise,cote,"En cours");

            this.dispose();
            Parieur_MonCompte Cparieur;
            try {
                Cparieur = new Parieur_MonCompte(email);
                Cparieur.setVisible(false);
                Cparieur.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(Parieur_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "saisir tous les information correctement et completement SVP", "Ohlala", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnParierMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnParier;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSimuler;
    private javax.swing.JComboBox<String> jCBEtape;
    private javax.swing.JComboBox<String> jCBRallye;
    private javax.swing.JComboBox<String> jComboBoxEdition;
    private javax.swing.JComboBox<String> jComboBoxEtape;
    private javax.swing.JComboBox<String> jComboBoxParticipant;
    private javax.swing.JComboBox<String> jComboBoxRallye;
    private javax.swing.JComboBox<String> jComboBoxVehicule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDistance;
    private javax.swing.JLabel jLabelDistanceSimuler;
    private javax.swing.JLabel jLabelEditionNouvelle;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelNbV;
    private javax.swing.JLabel jLabelNbVirage;
    private javax.swing.JLabel jLabelNiveauExp;
    private javax.swing.JLabel jLabelPoids;
    private javax.swing.JLabel jLabelPuissance;
    private javax.swing.JLabel jLabelTempsProbableMax;
    private javax.swing.JLabel jLabelTempsProbableMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCotation;
    private javax.swing.JFormattedTextField jTextMise;
    // End of variables declaration//GEN-END:variables
}
