/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import FFRAG.*;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author 21405117
 */
public class Parieur_Inscription extends javax.swing.JFrame {
    private Model_F mf;

    /**
     * Creates new form InscriptionParieur
     */
    public Parieur_Inscription() throws ParseException {
        initComponents();
        mf = new Model_F();
  
        
       
        this.setSize(820,600);
        this.setLocationRelativeTo(null);
        this.jTextEmail.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextEmailConnect = new javax.swing.JTextField();
        jButtonConnecter = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        errorMailConnexion = new javax.swing.JLabel();
        errorPasswordConnexion = new javax.swing.JLabel();
        jLabelConnexion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextPrenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jTextAdresse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextIBAN = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        errorName = new javax.swing.JLabel();
        errorPrenom = new javax.swing.JLabel();
        errorDate = new javax.swing.JLabel();
        errorMail = new javax.swing.JLabel();
        errorAdresse = new javax.swing.JLabel();
        errorIBAN = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordI = new javax.swing.JPasswordField();
        jPasswordI2 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        errorPasswordI = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelInscription = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Identifiez vous");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 30, 116, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email : ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 90, 60, 17);

        jTextEmailConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailConnectActionPerformed(evt);
            }
        });
        jPanel2.add(jTextEmailConnect);
        jTextEmailConnect.setBounds(160, 80, 208, 30);

        jButtonConnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/icons8-inconnexion-30.png"))); // NOI18N
        jButtonConnecter.setText("Connecter");
        jButtonConnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConnecterMouseClicked(evt);
            }
        });
        jButtonConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnecterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConnecter);
        jButtonConnecter.setBounds(567, 370, 160, 39);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mot de passe:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 160, 100, 17);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(160, 150, 208, 30);

        errorMailConnexion.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorMailConnexion.setForeground(new java.awt.Color(204, 0, 0));
        errorMailConnexion.setText("Saisir email");
        jPanel2.add(errorMailConnexion);
        errorMailConnexion.setBounds(170, 120, 270, 17);

        errorPasswordConnexion.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorPasswordConnexion.setForeground(new java.awt.Color(204, 0, 0));
        errorPasswordConnexion.setText(" ");
        jPanel2.add(errorPasswordConnexion);
        errorPasswordConnexion.setBounds(170, 200, 270, 17);

        jLabelConnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/NG2015_020215_091225_RB-820x547.jpg"))); // NOI18N
        jPanel2.add(jLabelConnexion);
        jLabelConnexion.setBounds(0, -80, 810, 700);

        jTabbedPane2.addTab("Connexion", jPanel2);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 60, 17);
        jPanel1.add(jTextNom);
        jTextNom.setBounds(170, 30, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prénom : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 67, 17);
        jPanel1.add(jTextPrenom);
        jTextPrenom.setBounds(170, 110, 153, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date de naissance : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 136, 17);

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setMinSelectableDate(new java.util.Date(-1577919521000L));
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(170, 190, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Adresse Mail : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 270, 100, 17);
        jPanel1.add(jTextAdresse);
        jTextAdresse.setBounds(170, 330, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Adresse : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 340, 68, 17);
        jPanel1.add(jTextEmail);
        jTextEmail.setBounds(170, 260, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("IBAN : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 410, 51, 17);
        jPanel1.add(jTextIBAN);
        jTextIBAN.setBounds(170, 400, 330, 30);

        jButtonValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/icons8-validate-30.png"))); // NOI18N
        jButtonValider.setText("Valider");
        jButtonValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValiderMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonValider);
        jButtonValider.setBounds(660, 480, 130, 40);

        errorName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorName.setForeground(new java.awt.Color(204, 0, 0));
        errorName.setText(" ");
        jPanel1.add(errorName);
        errorName.setBounds(170, 70, 250, 17);

        errorPrenom.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorPrenom.setForeground(new java.awt.Color(204, 0, 0));
        errorPrenom.setText(" ");
        jPanel1.add(errorPrenom);
        errorPrenom.setBounds(170, 150, 230, 17);

        errorDate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorDate.setForeground(new java.awt.Color(204, 0, 0));
        errorDate.setText(" ");
        jPanel1.add(errorDate);
        errorDate.setBounds(170, 230, 330, 17);

        errorMail.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorMail.setForeground(new java.awt.Color(204, 0, 0));
        errorMail.setText(" ");
        jPanel1.add(errorMail);
        errorMail.setBounds(170, 300, 250, 17);

        errorAdresse.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorAdresse.setForeground(new java.awt.Color(204, 0, 0));
        errorAdresse.setText(" ");
        jPanel1.add(errorAdresse);
        errorAdresse.setBounds(170, 370, 250, 17);

        errorIBAN.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorIBAN.setForeground(new java.awt.Color(204, 0, 0));
        errorIBAN.setText(" ");
        jPanel1.add(errorIBAN);
        errorIBAN.setBounds(170, 440, 250, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Mot de passe :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 480, 100, 14);
        jPanel1.add(jPasswordI);
        jPasswordI.setBounds(170, 470, 130, 30);
        jPanel1.add(jPasswordI2);
        jPasswordI2.setBounds(440, 470, 140, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Confirmer :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 480, 90, 17);

        errorPasswordI.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        errorPasswordI.setForeground(new java.awt.Color(204, 0, 0));
        errorPasswordI.setText(" ");
        jPanel1.add(errorPasswordI);
        errorPasswordI.setBounds(170, 510, 320, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/icons8-remove-30.png"))); // NOI18N
        jButton1.setText("Effacer");
        jPanel1.add(jButton1);
        jButton1.setBounds(660, 410, 130, 40);

        jLabelInscription.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelInscription.setForeground(new java.awt.Color(204, 0, 0));
        jLabelInscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/NG2015_020215_091225_RB-820x547.jpg"))); // NOI18N
        jPanel1.add(jLabelInscription);
        jLabelInscription.setBounds(0, -200, 810, 950);

        jTabbedPane2.addTab("Inscription", jPanel1);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 820, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderMouseClicked

        String dateNaissance = null;
        Boolean emptyFormulaire = true;
        Boolean valideMail =false;
        Boolean validePassword =false;
        errorName.setText("");
        errorPrenom.setText("");
        errorDate.setText("");
        errorMail.setText("");
        errorAdresse.setText("");
        errorIBAN.setText("");
        errorPasswordI.setText("");

        if (jTextNom.getText().trim().isEmpty()){
            errorName.setText("Veulliez entrer votre nom");
            emptyFormulaire = true;
        }else{
            emptyFormulaire = false;
        }
        if (jTextPrenom.getText().trim().isEmpty()){
            errorPrenom.setText("Veulliez entrer votre prenom");
            emptyFormulaire = true;
        }else{
            emptyFormulaire = false;
        }
        if (jDateChooser1.getDate() == null){
            errorDate.setText("Veulliez choisir votre date de naissance");
            emptyFormulaire = true;
        }else{
            emptyFormulaire = false;
        }
        if (jTextEmail.getText().equals("")){
            errorMail.setText("Veulliez entrez votre adresse mail");
            emptyFormulaire = true;
        }else{
            emptyFormulaire = false;
        }
        if (jTextAdresse.getText().trim().isEmpty()){
            errorAdresse.setText("Veulliez entrer votre adresse");
            emptyFormulaire = true;
        }else{
            emptyFormulaire = false;
        }
        if (jTextIBAN.getText().trim().isEmpty()){
            errorIBAN.setText("Veulliez entrer votre IBAN");
            emptyFormulaire = true;
        }else{
            emptyFormulaire = false;
        }
        //verifier email
        for(Parieur parieur: this.mf.getListParieur()){
            if(!parieur.getEmail().equals(this.jTextEmail.getText()) ){
                errorMail.setText("veuillez rentrez une adresse mail valide");
                emptyFormulaire = true;
            }
        }

        if (jPasswordI.getText().trim().isEmpty()){
            errorPasswordI.setText("Veulliez entrer un mot de passe");
            emptyFormulaire = true;
        }else{
            if (jPasswordI2.getText().trim().isEmpty()){
                errorPasswordI.setText("Veulliez confimer le mot de passe");
            }else{
                emptyFormulaire = false;
                //verifier mot de passe
                if (jPasswordI.getText().equals(jPasswordI2.getText())){
                    validePassword = true;
                }else{
                    errorPasswordI.setText("Les mots de passe ne sont pas identiques");
                }
            }
        }

        // verifier est ce que ce mail existe deja dans la base de donnees

        if(!emptyFormulaire && validePassword){

            try {

                Calendar now = Calendar.getInstance();
                Calendar dob = Calendar.getInstance();
                dob.setTime(jDateChooser1.getDate());
                int year1 = now.get(Calendar.YEAR);
                int year2 = dob.get(Calendar.YEAR);
                int age = year1 - year2;
                int month1 = now.get(Calendar.MONTH);
                int month2 = dob.get(Calendar.MONTH);
                if (month2 > month1) {
                    age--;
                } else if (month1 == month2) {
                    int day1 = now.get(Calendar.DAY_OF_MONTH);
                    int day2 = dob.get(Calendar.DAY_OF_MONTH);
                    if (day2 > day1) {
                        age--;
                    }
                }
                String ageS = String.valueOf(age);
                this.mf.enregistrerParieur(jTextEmail.getText(),jPasswordI.getText(), jTextNom.getText(), jTextPrenom.getText(),ageS, jTextAdresse.getText(), jTextIBAN.getText());

                this.dispose();
                Parieur_MonCompte Cparieur = new Parieur_MonCompte(this.jTextEmail.getText());
                this.setVisible(false);
                Cparieur.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(Parieur_Inscription.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonValiderMouseClicked

    private void jButtonConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnecterActionPerformed

    }//GEN-LAST:event_jButtonConnecterActionPerformed

    private void jButtonConnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConnecterMouseClicked
        // TODO add your handling code here:

        if(this.jTextEmailConnect.getText().isEmpty()){
            errorMailConnexion.setText("veuillez rentrez votre adresse mail");
        }else{
            for(Parieur parieur: this.mf.getListParieur()){
                if(!parieur.getEmail().equals(this.jTextEmailConnect.getText()) /*|| !this.jTextEmailConnect.isValid() to validate format but don't know anyway i'll try to do another thing :D*/){
                    errorMailConnexion.setText("veuillez rentrez une adresse mail valide");

                }else{
                    //errorMailConnexion.setText("");
                    if(this.jPasswordField1.getText().isEmpty()){
                        errorPasswordConnexion.setText("veuillez rentrez votre mot de passe");

                    }else{
                        if(parieur.getMotdePasse().equals(this.jPasswordField1.getText())){
                            Parieur_MonCompte Cparieur;
                            try {
                                Cparieur = new Parieur_MonCompte(this.jTextEmailConnect.getText());
                                this.setVisible(false);
                                Cparieur.setVisible(true);
                            } catch (ParseException ex) {
                                Logger.getLogger(Parieur_Inscription.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }else{
                            errorPasswordConnexion.setText("Oups! mot de passe incorrect");
                            break;
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_jButtonConnecterMouseClicked

    private void jTextEmailConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailConnectActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorAdresse;
    private javax.swing.JLabel errorDate;
    private javax.swing.JLabel errorIBAN;
    private javax.swing.JLabel errorMail;
    private javax.swing.JLabel errorMailConnexion;
    private javax.swing.JLabel errorName;
    private javax.swing.JLabel errorPasswordConnexion;
    private javax.swing.JLabel errorPasswordI;
    private javax.swing.JLabel errorPrenom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConnecter;
    private javax.swing.JButton jButtonValider;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConnexion;
    private javax.swing.JLabel jLabelInscription;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordI;
    private javax.swing.JPasswordField jPasswordI2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextAdresse;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmailConnect;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextIBAN;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextPrenom;
    // End of variables declaration//GEN-END:variables
}
